display ip from 'X-Real-IP' header if behind proxy
SFTtech/sftdyn pull request #9
Opened 2019-07-23 22:09 UTC by bbx-github

Before localhost ip was displayed. I hope nothing else breaks.

2019-07-25 15:56 UTC, TheJJ requested changes
good idea. I'd suggest to implement it differently though:
add a new function to the sample config file, called `def get_ip(source_ip, headers)`, where the mapping can be done in any fancy way. As default, sample implementation would be:

``` python
def get_ip(source_ip, headers):
    if 'X-Real-IP' in headers:
        source_ip = headers['X-Real-IP']
    return source_ip
```

This function is then called in line 85 of the `handle_request` method. That way, IP mappings can be customized even by a database easily, or the header can be renamed, etc.

2019-07-25 16:53 UTC, bbx-github commented
Does this match your expectations? It still has this `if headers` to not call `get_ip` and get an exception.

2019-07-26 09:30 UTC, TheJJ requested changes

2019-07-26 09:30 UTC, TheJJ commented on sftdyn/server.py
> +            headers = dict()
as the `get_ip` function also works if the headers are empty, you can just do a call like this:
``` python
if headers is None:
    headers = dict()
ip = self.get_ip(ip, headers)
```

2019-07-26 09:30 UTC, TheJJ commented on etc/sample.conf
> +def get_ip(source_ip, headers):
as this happens before the `nsupdatecommands`, I'd move this function above it.

2019-07-26 22:38 UTC, bbx-github commented
Was this really necessary? I thought the config gets imported by `args.py` and then functions order does not matter.

2019-07-26 22:56 UTC, TheJJ commented
That's true, but as this is an example config file it's easier to understand what happens if the functions are written in their logical order.

2019-07-26 23:03 UTC, TheJJ approved these changes
looking good now :)

2019-07-26 23:58 UTC, TheJJ requested changes
ah, you also need to register the function in `Server`, just like it is done with `nsupdatecommands`.

2019-07-29 14:16 UTC, bbx-github commented
Oh - yes. Obviously I did not understand how it works. And obviously I did not use this code but my simple fix. Anyway I like to add this feature. So I will do a installation of this code for testing.
I think this should be an optional configuration because with a simple setup it is not needed.

2019-07-29 15:08 UTC, bbx-github commented
I did setup setup a installation for testing and now it works with and without `def get_ip` in config.

2019-07-30 12:24 UTC, TheJJ approved these changes
nice!

2019-07-30 12:25 UTC, merged